# Generated by Django 5.1.15 on 2026-07-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="date_approved",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="request",
            name="date_cancelled",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="request",
            name="date_ordered",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="request",
            name="date_received",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="request",
            name="date_requested",
            field=models.DateField(blank=True, null=True),
        ),
    ]
