# Generated by Django 5.1.15 on 2026-07-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0002_request_date_approved_request_date_cancelled_and_more"),
        ("tenancy", "0010_lab_default_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingaddress",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="shippingaddress",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("lab",),
                name="unique_default_shipping_address_per_lab",
            ),
        ),
    ]
