# Generated by Django 5.1.15 on 2026-07-03 07:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0003_shippingaddress_is_default_and_more"),
        ("tenancy", "0010_lab_default_currency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="budget",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("lab",),
                name="unique_default_budget_per_lab",
            ),
        ),
    ]
