# Generated by Django 5.1.15 on 2026-07-03 08:49

from django.db import migrations, models


def _untracked_request_ids(apps):
    """PKs of requests that were received-untracked in-app (per the audit trail)."""
    AuditEntry = apps.get_model("audit", "AuditEntry")
    entries = AuditEntry.objects.filter(
        action="procurement.request_delivered_untracked", target_type="Request"
    ).values_list("target_id", flat=True)
    return [int(target_id) for target_id in entries if target_id.isdigit()]


def mark_untracked_as_received(apps, schema_editor):
    """Move requests received-untracked in-app from Delivered to the new terminal
    Received status. Imported "delivered" orders have no such audit entry and stay
    Delivered (still awaiting check-in)."""
    Request = apps.get_model("procurement", "Request")
    Request.objects.filter(pk__in=_untracked_request_ids(apps), status="delivered").update(
        status="received"
    )


def mark_received_as_delivered(apps, schema_editor):
    Request = apps.get_model("procurement", "Request")
    Request.objects.filter(pk__in=_untracked_request_ids(apps), status="received").update(
        status="delivered"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0001_initial"),
        ("procurement", "0004_budget_is_default_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("ordered", "Ordered"),
                    ("delivered", "Delivered"),
                    ("received", "Received"),
                    ("checked_in", "Checked in"),
                    ("cancelled", "Cancelled"),
                ],
                default="requested",
                max_length=16,
            ),
        ),
        migrations.RunPython(mark_untracked_as_received, mark_received_as_delivered),
    ]
