# Generated by Django 5.1.15 on 2026-07-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_seed_hazard_statements"),
        ("procurement", "0005_alter_request_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="hazards",
            field=models.ManyToManyField(
                blank=True, related_name="requests", to="inventory.hazardstatement"
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="signal_word",
            field=models.CharField(
                blank=True,
                choices=[("", "None"), ("warning", "Warning"), ("danger", "Danger")],
                default="",
                max_length=10,
            ),
        ),
    ]
