# Generated by Django 5.1.15 on 2026-07-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0006_request_hazards_request_signal_word"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="storage_class",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Lagerklasse (TRGS 510)"
            ),
        ),
    ]
