# Generated by Django 5.1.15 on 2026-07-08 19:49

import apps.procurement.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0008_request_forward_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='procurement_route',
            field=models.CharField(choices=[('direct', 'Direct order'), ('central', 'Central purchasing (Zentraleinkauf)')], default='direct', max_length=16, verbose_name='procurement route'),
        ),
        migrations.AddField(
            model_name='request',
            name='zk_order_number',
            field=models.CharField(blank=True, max_length=64, verbose_name='ZK order #'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='country',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('po_created', 'PO created'), ('po_signed', 'PO signed'), ('po_sent', 'PO sent'), ('ordered', 'Ordered'), ('delivered', 'Delivered'), ('received', 'Received'), ('checked_in', 'Checked in'), ('cancelled', 'Cancelled')], default='requested', max_length=16),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded')], default='active', max_length=16)),
                ('po_snapshot_net', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unsigned_pdf', models.FileField(upload_to=apps.procurement.models.purchase_order_upload_path)),
                ('signed_pdf', models.FileField(blank=True, upload_to=apps.procurement.models.purchase_order_upload_path)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_created', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='procurement.request')),
                ('signed_uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_signed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
