# Generated by Django 5.1.15 on 2026-06-30 14:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0003_seed_permissions_and_template_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lab",
            name="default_vat_rate",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.19"), max_digits=5
            ),
        ),
    ]
