# Generated by Django 5.1.15 on 2026-07-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0005_purchase_coordinator_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="approval_notifications",
            field=models.CharField(
                choices=[
                    ("immediate", "Every email"),
                    ("daily", "Daily summary"),
                    ("off", "No email"),
                ],
                default="immediate",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="request_update_notifications",
            field=models.CharField(
                choices=[
                    ("immediate", "Every email"),
                    ("daily", "Daily summary"),
                    ("off", "No email"),
                ],
                default="immediate",
                max_length=16,
            ),
        ),
    ]
