# Generated by Django 5.1.15 on 2026-07-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0007_self_approve_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="friendly_name",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="friendly name"
            ),
        ),
    ]
