# Generated by Django 5.1.15 on 2026-07-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0009_alter_user_email_user_tenancy_user_email_ci_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="lab",
            name="default_currency",
            field=models.CharField(default="EUR", max_length=3),
        ),
    ]
