# Generated by Django 5.1.15 on 2026-07-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0011_accept_forwards_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="onboarding_seen_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="onboarding seen at"
            ),
        ),
    ]
