# Generated by Django 5.1.15 on 2026-07-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0012_user_onboarding_seen_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="expiry_days_ahead",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (7, "7 days ahead"),
                    (14, "14 days ahead"),
                    (30, "30 days ahead"),
                ],
                default=30,
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="expiry_notifications",
            field=models.CharField(
                choices=[
                    ("weekly_all", "Once a week — all items"),
                    ("weekly_new", "Once a week — only newly expired items"),
                    ("off", "Never"),
                ],
                default="weekly_new",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="expiry_owned_only",
            field=models.BooleanField(default=False),
        ),
    ]
