# Generated by Django 5.1.15 on 2026-07-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0013_membership_expiry_days_ahead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='central_purchasing_threshold_net',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='central purchasing threshold (net)'),
        ),
        migrations.AddField(
            model_name='lab',
            name='po_deviation_threshold_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='PO price deviation threshold (%)'),
        ),
    ]
