# Generated by Django 5.1.15 on 2026-06-30 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0002_lab_permission_role_membership_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HazardStatement",
            fields=[
                (
                    "code",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("H", "Hazard (H)"),
                            ("EUH", "EU Hazard (EUH)"),
                            ("P", "Precautionary (P)"),
                        ],
                        max_length=4,
                    ),
                ),
                ("text_en", models.CharField(blank=True, max_length=500)),
                ("text_de", models.CharField(blank=True, max_length=500)),
                ("category", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("room_number", models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="FieldDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=64)),
                ("label", models.CharField(max_length=200)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("date", "Date"),
                            ("boolean", "Boolean"),
                        ],
                        default="text",
                        max_length=16,
                    ),
                ),
                (
                    "lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_definitions",
                        to="tenancy.lab",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FieldPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "fields",
                    models.ManyToManyField(
                        blank=True,
                        related_name="presets",
                        to="inventory.fielddefinition",
                    ),
                ),
                (
                    "lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_presets",
                        to="tenancy.lab",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("human_id", models.CharField(max_length=64)),
                (
                    "legacy_serial",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("barcode", models.CharField(blank=True, max_length=128)),
                ("name", models.CharField(max_length=500)),
                (
                    "price_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("price_currency", models.CharField(blank=True, max_length=3)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("lot_number", models.CharField(blank=True, max_length=128)),
                ("catalog_number", models.CharField(blank=True, max_length=128)),
                ("cas_number", models.CharField(blank=True, max_length=64)),
                (
                    "signal_word",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "None"),
                            ("warning", "Warning"),
                            ("danger", "Danger"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "wgk",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        verbose_name="Wassergefährdungsklasse",
                    ),
                ),
                (
                    "storage_class",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Lagerklasse (TRGS 510)"
                    ),
                ),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                (
                    "hazards",
                    models.ManyToManyField(
                        blank=True, related_name="items", to="inventory.hazardstatement"
                    ),
                ),
                (
                    "lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="tenancy.lab",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
