# Generated by Django 5.1.15 on 2026-06-30 14:49

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        ("procurement", "0001_initial"),
        ("tenancy", "0002_lab_permission_role_membership_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="procurement.vendor",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="lab",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="tenancy.lab",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="inventory.location",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="inventory.location",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="lab",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="tenancy.lab",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="items", to="inventory.tag"
            ),
        ),
        migrations.AddConstraint(
            model_name="fielddefinition",
            constraint=models.UniqueConstraint(
                fields=("lab", "key"), name="unique_field_key_per_lab"
            ),
        ),
        migrations.AddConstraint(
            model_name="fieldpreset",
            constraint=models.UniqueConstraint(
                fields=("lab", "name"), name="unique_preset_per_lab"
            ),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                fields=("lab", "parent", "name"), name="unique_location_per_parent"
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                fields=("lab", "name"), name="unique_tag_per_lab"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["lab", "name"], name="inventory_i_lab_id_daa6a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["custom_fields"], name="item_custom_fields_gin"
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                fields=("lab", "human_id"), name="unique_human_id_per_lab"
            ),
        ),
    ]
