# Generated by Django 5.1.15 on 2026-07-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_seed_hazard_statements"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="product_url",
            field=models.URLField(blank=True),
        ),
    ]
