# Generated by Django 5.1.15 on 2026-06-30 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0002_lab_permission_role_membership_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("action", models.CharField(max_length=64)),
                ("target_type", models.CharField(max_length=64)),
                ("target_id", models.CharField(blank=True, max_length=64)),
                ("changes", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_entries",
                        to="tenancy.lab",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "audit entries",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["lab", "-timestamp"],
                        name="audit_audit_lab_id_a46675_idx",
                    ),
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="audit_audit_target__e2abcf_idx",
                    ),
                ],
            },
        ),
    ]
